apiVersion: v1
kind: ConfigMap
metadata:
  name: kevinhuaman-api-config
  namespace: kevinhuaman-api-ns
  labels:
    app: kevinhuaman-api

data:
  APP_ENV: "produccion"
  APP_PORT: "8085"
  APP_VERSION: "1.0.0"